# Data

## Data Source

Our data was collected from the New York Times, which is an American daily newspaper based in New York City with a worldwide readership. The data is held on New York Times COVID-19 Github repository. The data is updating itself every day by the end of day and the latest update will be today, when we are doing our analysis. This dataset includes cumulative cases and deaths reported in each state across the U.S., including U.S. territories and the District of Columbia, since the beginning of the pandemic beginning in Jan 21, 2021. 

Website for our data source: https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv

## Data Dictionary

Variable Name            | Description
-------------------------| -------------
date                     | Date
state                    | Name of State
fips                     | First Two Digits of ZipCode of the State
cases                    | Number of Cumulative Cases
deaths                   | Number of Cumulative Deaths

