# Data Cleaning

```{r message=FALSE, warning=FALSE}
#load packages
library(bayesrules)
library(tidyverse)
library(janitor)
library(rstanarm)
library(bayesplot)
library(tidybayes)
library(broom.mixed)
library(modelr)
library(e1071)
library(forcats)
library(ggExtra)
library(ggpubr)
library(ggridges)
library(devtools)
library(zoo)
library(DT)
library(dplyr)
library(plyr)
```
## Load Data

```{r message=FALSE, warning=FALSE}
#load data
covid19 <- read_csv(url("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv"))
newdata <- read.csv("C:/Users/qianz/Desktop/Macalester/Junior 1st semester/STAT 454/COVID-bookdown/bookdown-demo-main/prediction_newdata.csv")
```

## Generate Monthly Incident Data

```{r}
covid19_filter <- covid19 %>%
  dplyr::group_by(state) %>%
  dplyr::mutate(lag1 = lag(cases, n = 1)) 

covid19_filter$lag1 <- covid19_filter$lag1 %>% 
  replace_na(0)

covid19_filter <- covid19_filter %>% mutate(case_new = cases - lag1) 
```

## Generate Time Variables

```{r message=FALSE, warning=FALSE}
covid19_month <- covid19_filter %>%
  dplyr::mutate(year = lubridate::year(date), 
                month = lubridate::month(date), 
                day = lubridate::day(date)) %>%
  dplyr::group_by(state, year, month) %>%
  dplyr::summarize(cases = sum(case_new)) 

covid19_month$Date <- as.yearmon(paste(covid19_month$year, covid19_month$month), "%Y %m")
```

## Remove Incomplete Monthly Data

```{r}
covid19_month <- covid19_month %>%
  filter(!(year == 2021 & month == 12))
```

## Generate Lag in Time-Series

```{r}
covid19_month <- covid19_month %>%
  dplyr::group_by(state) %>%
  dplyr::mutate(lag1 = lag(cases, n = 1)) 

covid19_month$lag1 <- covid19_month$lag1 %>% 
  replace_na(0)

covid19_month <- covid19_month %>%
  dplyr::group_by(state) %>%
  mutate(lag3 = lag(cases, n = 3)) 

covid19_month$lag3 <- covid19_month$lag3 %>% 
  replace_na(0)

covid19_month <- covid19_month %>%
  dplyr::group_by(state) %>%
  mutate(lag6 = lag(cases, n = 6)) 

covid19_month$lag6 <- covid19_month$lag6 %>% 
  replace_na(0)
```

## Clean undefined values (0) in Logarithmic function

```{r}

covid19_month$lag1 <- covid19_month$lag1 + 1
covid19_month$lag3 <- covid19_month$lag3 + 1
covid19_month$lag6 <- covid19_month$lag6 + 1

covid19_month <- covid19_month %>%
  mutate(lag1_log = log(lag1) + 1) %>%
  mutate(lag3_log = log(lag3) + 1) %>%
  mutate(lag6_log = log(lag6) + 1)
```

## Generate Season Variable

```{r}
covid19_month <-covid19_month %>%
  mutate(season = ifelse(month >= 3 & month <=5 , "spring", ifelse(month >= 6 & month <=8, "summer", ifelse(month >= 9 & month <= 11, "fall", "winter"))))
```

## Rename and Clean New Data

```{r}
newdata <- plyr::rename(newdata, c("Alabama" = "state",  "X2022" = "year", "X1" = "month"))
newdata <- newdata %>%
  mutate(year = ifelse(month == 12, 2021, 2022))
newdata$Date <- as.yearmon(paste(newdata$year, newdata$month), "%Y %m")
```


```{r}
covid19_whole <- rbind.fill(newdata, covid19_month)
```

```{r}
covid19_whole <-covid19_whole %>%
  mutate(season = ifelse(month >= 3 & month <=5 , "spring", ifelse(month >= 6 & month <=8, "summer", ifelse(month >= 9 & month <= 11, "fall", "winter"))))
```

```{r}
covid19_whole <- covid19_whole %>%
  dplyr::group_by(state) %>%
  dplyr::arrange(Date) %>%
  dplyr::mutate(lag1 = ifelse(is.na(lag1), lag(cases, n = 1), lag1)) %>%
  dplyr::mutate(lag3 = ifelse(is.na(lag3), lag(cases, n = 3), lag3)) %>%
  dplyr::mutate(lag6 = ifelse(is.na(lag6), lag(cases, n = 6), lag6)) 

covid19_whole$lag1 <- covid19_whole$lag1 + 1
covid19_whole$lag3 <- covid19_whole$lag3 + 1
covid19_whole$lag6 <- covid19_whole$lag6 + 1

covid19_whole <- covid19_whole %>%
  mutate(lag1_log = log(lag1) + 1) %>%
  mutate(lag3_log = log(lag3) + 1) %>%
  mutate(lag6_log = log(lag6) + 1)
```

## Generate Testing Dataset

```{r}
covid19_test <- covid19_whole %>%
  filter(!is.na(lag1) & year == 2021 & month == 12 & !is.na(lag6)) %>%
  select(-cases)
```


